import { defineConfig } from "oxlint";

// oxlint is the only linter. Its rule set is Biome's recommended set mapped
// rule-by-rule, plus the vendored anti-slop plugin and jsx-sort-props. Type-aware
// rules are skipped unless --type-aware is passed.
export default defineConfig({
	plugins: [
		"typescript",
		"unicorn",
		"react",
		"jsx-a11y",
		"import",
		"promise",
		"oxc",
		"node",
	],
	categories: {
		correctness: "off",
		suspicious: "off",
		pedantic: "off",
		perf: "off",
		style: "off",
		restriction: "off",
	},
	ignorePatterns: [
		"src/routeTree.gen.ts",
		"src/generated/**",
		"src/shared/ui/**",
		"tools/oxlint/anti-slop/**",
		"scripts/**",
		"e2e/**",
		".agents/**",
		".claude/**",
		".codex/**",
		".cursor/**",
		".gemini/**",
	],
	jsPlugins: [
		{ name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
		{ name: "sort-props", specifier: "./tools/oxlint/sort-props/index.ts" },
		{ name: "tanstack-query", specifier: "./tools/oxlint/tanstack/query.ts" },
		{ name: "tanstack-router", specifier: "./tools/oxlint/tanstack/router.ts" },
		"oxlint-tailwindcss",
	],
	settings: { tailwindcss: { entryPoint: "src/styles.css" } },
	rules: {
		// Replaces Biome useSortedAttributes; ignoreCase matches its ordering.
		"sort-props/jsx-sort-props": ["error", { ignoreCase: true }],
		"tanstack-query/exhaustive-deps": "error",
		"tanstack-query/infinite-query-property-order": "error",
		"tanstack-query/mutation-property-order": "error",
		"tanstack-query/no-rest-destructuring": "error",
		"tanstack-query/no-unstable-deps": "error",
		"tanstack-query/no-void-query-fn": "error",
		// Off: opt-in, and it has no notion of prefix invalidation. Most hits were
		// invalidateQueries({ queryKey: ["documents"] }) covering seven queries at
		// once, which is the point, not a hand-typed key that can drift.
		"tanstack-query/prefer-query-options": "off",
		"tanstack-query/stable-query-client": "error",
		"tanstack-router/create-route-property-order": "error",
		"tanstack-router/route-param-names": "error",
		"typescript/no-deprecated": "error",
		"tailwindcss/consistent-variant-order": "error",
		"tailwindcss/enforce-canonical": "error",
		"tailwindcss/enforce-consistent-important-position": "error",
		"tailwindcss/enforce-consistent-variable-syntax": "error",
		"tailwindcss/enforce-negative-arbitrary-values": "error",
		"tailwindcss/enforce-shorthand": "error",
		"tailwindcss/no-conflicting-classes": "error",
		"tailwindcss/no-contradicting-variants": "error",
		"tailwindcss/no-dark-without-light": "error",
		"tailwindcss/no-hardcoded-colors": "error",
		"tailwindcss/no-unnecessary-arbitrary-value": "error",
		"tailwindcss/no-deprecated-classes": "error",
		"tailwindcss/no-duplicate-classes": "error",
		"tailwindcss/no-unknown-classes": "error",
		"tailwindcss/no-unnecessary-whitespace": "error",
		"array-callback-return": "error",
		"constructor-super": "error",
		"default-case-last": "error",
		eqeqeq: ["error", "always", { null: "ignore" }],
		"for-direction": "error",
		"getter-return": "error",
		// Off: bans `import * as x`. Biome's noDynamicNamespaceImportAccess only
		// flagged dynamic member access on such an import - 8 hits, all idiomatic.
		"import/no-namespace": "off",
		"jsx-a11y/alt-text": "error",
		"jsx-a11y/anchor-ambiguous-text": "error",
		"jsx-a11y/anchor-has-content": "error",
		"jsx-a11y/anchor-is-valid": "error",
		"jsx-a11y/aria-activedescendant-has-tabindex": "error",
		"jsx-a11y/aria-props": "error",
		"jsx-a11y/aria-proptypes": "error",
		"jsx-a11y/aria-role": "error",
		"jsx-a11y/aria-unsupported-elements": "error",
		"jsx-a11y/autocomplete-valid": "error",
		"jsx-a11y/click-events-have-key-events": "error",
		"jsx-a11y/heading-has-content": "error",
		"jsx-a11y/html-has-lang": "error",
		"jsx-a11y/iframe-has-title": "error",
		"jsx-a11y/img-redundant-alt": "error",
		"jsx-a11y/interactive-supports-focus": "error",
		"jsx-a11y/label-has-associated-control": "error",
		"jsx-a11y/lang": "error",
		"jsx-a11y/media-has-caption": "error",
		"jsx-a11y/mouse-events-have-key-events": "error",
		"jsx-a11y/no-access-key": "error",
		"jsx-a11y/no-aria-hidden-on-focusable": "error",
		// ignoreNonDOM: every hit is the first field of a modal, where moving focus in
		// is the WAI-ARIA dialog pattern. Raw <input autoFocus> is still reported.
		"jsx-a11y/no-autofocus": ["error", { ignoreNonDOM: true }],
		"jsx-a11y/no-distracting-elements": "error",
		"jsx-a11y/no-interactive-element-to-noninteractive-role": "error",
		"jsx-a11y/no-noninteractive-element-to-interactive-role": "error",
		"jsx-a11y/no-noninteractive-tabindex": "error",
		"jsx-a11y/no-redundant-roles": "error",
		"jsx-a11y/no-static-element-interactions": "error",
		// Off: its advice is wrong here - <output> for a role="status" live region,
		// <img> for an inline <svg role="img">, <select> for a custom combobox.
		// Biome's useSemanticElements, which this replaces, flagged none of them.
		"jsx-a11y/prefer-tag-over-role": "off",
		"jsx-a11y/role-has-required-aria-props": "error",
		"jsx-a11y/role-supports-aria-props": "error",
		"jsx-a11y/scope": "error",
		"jsx-a11y/tabindex-no-positive": "error",
		"no-array-constructor": "error",
		"no-async-promise-executor": "error",
		"no-case-declarations": "error",
		"no-class-assign": "error",
		"no-compare-neg-zero": "error",
		"no-const-assign": "error",
		"no-constant-condition": "error",
		"no-constructor-return": "error",
		// Off: blanket ban on `continue`. Biome's noUselessContinue only flagged a
		// trailing one, so this is a new opinion, not the equivalent - 49 hits.
		"no-continue": "off",
		"no-control-regex": "error",
		"no-debugger": "error",
		"no-dupe-class-members": "error",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-eval": "error",
		"no-ex-assign": "error",
		"no-extra-boolean-cast": "error",
		"no-extra-label": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-global-assign": "error",
		"no-import-assign": "error",
		"no-inner-declarations": "error",
		"no-irregular-whitespace": "error",
		"no-label-var": "error",
		"no-labels": "error",
		"no-lone-blocks": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "error",
		"no-nonoctal-decimal-escape": "error",
		"no-obj-calls": "error",
		"no-proto": "error",
		"no-prototype-builtins": "error",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-script-url": "error",
		"no-self-assign": "error",
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-setter-return": "error",
		"no-shadow-restricted-names": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "error",
		"no-this-before-super": "error",
		"no-unneeded-ternary": "error",
		"no-unreachable": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unsafe-optional-chaining": "error",
		"no-unused-labels": "error",
		"no-unused-private-class-members": "error",
		"no-unused-vars": [
			"error",
			{
				argsIgnorePattern: "^_",
				varsIgnorePattern: "^_",
				caughtErrorsIgnorePattern: "^_",
				ignoreRestSiblings: true,
			},
		],
		"no-use-before-define": "off",
		"no-useless-backreference": "error",
		"no-useless-catch": "error",
		"no-useless-computed-key": "error",
		"no-useless-constructor": "error",
		"no-useless-escape": "error",
		"no-useless-rename": "error",
		"no-with": "error",
		"oxc/approx-constant": "error",
		"oxc/bad-min-max-func": "error",
		"oxc/misrefactored-assign-op": "error",
		"oxc/no-accumulating-spread": "error",
		"oxc/no-const-enum": "error",
		"prefer-arrow-callback": "error",
		"prefer-const": "error",
		"prefer-exponentiation-operator": "error",
		"prefer-numeric-literals": "error",
		"prefer-object-has-own": "error",
		"prefer-regex-literals": "error",
		"prefer-rest-params": "error",
		"prefer-template": "error",
		radix: "error",
		"react/button-has-type": "error",
		"react/exhaustive-deps": "error",
		// React Compiler is on (vite.config.ts). Denylist of APIs that break under
		// memoization; 0 hits today because Table v9's useTable is not on it.
		"react/incompatible-library": "error",
		"react/jsx-key": "error",
		"react/jsx-no-comment-textnodes": "error",
		"react/jsx-no-duplicate-props": "error",
		"react/jsx-no-script-url": "error",
		"react/jsx-no-target-blank": "error",
		// allowExpressions: wrapping a ReactNode in a fragment is how a component
		// returns it as an element; Biome's noUselessFragments allowed that too.
		"react/jsx-no-useless-fragment": ["error", { allowExpressions: true }],
		"react/no-array-index-key": "off",
		"react/no-children-prop": "error",
		"react/no-danger": "error",
		"react/no-danger-with-children": "error",
		"react/no-render-return-value": "error",
		"react/no-string-refs": "error",
		"react/rules-of-hooks": "error",
		"react/void-dom-elements-no-children": "error",
		"require-yield": "error",
		"typescript/adjacent-overload-signatures": "error",
		"typescript/ban-ts-comment": "error",
		"typescript/ban-types": "error",
		"typescript/consistent-type-exports": "error",
		"typescript/consistent-type-imports": [
			"error",
			{ disallowTypeAnnotations: false },
		],
		"typescript/dot-notation": "error",
		"typescript/no-duplicate-enum-values": "error",
		"typescript/no-empty-interface": "error",
		"typescript/no-empty-object-type": "error",
		"typescript/no-explicit-any": "error",
		"typescript/no-extra-non-null-assertion": "error",
		"typescript/no-extraneous-class": "error",
		"typescript/no-invalid-void-type": "error",
		"typescript/no-misused-new": "error",
		"typescript/no-non-null-asserted-optional-chain": "error",
		"typescript/no-non-null-assertion": "error",
		"typescript/no-this-alias": "error",
		"typescript/no-unnecessary-type-constraint": "error",
		"typescript/no-unsafe-declaration-merging": "error",
		"typescript/no-useless-empty-export": "error",
		"typescript/prefer-function-type": "error",
		"typescript/prefer-literal-enum-member": "error",
		"typescript/prefer-namespace-keyword": "error",
		"typescript/prefer-optional-chain": "error",
		"typescript/strict-void-return": "error",
		"unicorn/new-for-builtins": "error",
		"unicorn/no-document-cookie": "error",
		"unicorn/no-instanceof-array": "error",
		"unicorn/no-static-only-class": "error",
		"unicorn/no-thenable": "error",
		"unicorn/no-useless-switch-case": "error",
		"unicorn/prefer-array-flat-map": "error",
		"unicorn/prefer-array-index-of": "error",
		"unicorn/prefer-date-now": "error",
		"unicorn/prefer-dom-node-text-content": "error",
		"unicorn/prefer-math-min-max": "error",
		"unicorn/prefer-node-protocol": "error",
		"unicorn/prefer-number-properties": "error",
		"use-isnan": "error",
		"valid-typeof": "error",
		"anti-slop/no-chained-type-assertions": "error",
		"anti-slop/no-conditional-empty-object-spread": "error",
		"anti-slop/no-known-value-widening": "error",
		"anti-slop/no-module-mocking": "error",
		"anti-slop/no-object-parameters": "error",
		"anti-slop/no-reflect-apply": "error",
		"anti-slop/no-reflect-get": "error",
		"anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
		"anti-slop/no-unknown-parameters": "error",
		"anti-slop/no-unknown-returns": "error",
		"anti-slop/no-unknown-type-aliases": "error",
		"anti-slop/no-unsafe-dictionary-type": "error",
		"anti-slop/no-widen-then-assert": "error",
		"anti-slop/require-safety-comment-for-type-assertion": "error",
		// Off: a substring ban with no escape hatch, and most hits are zod's .shape.
		"anti-slop/no-shape-in-symbol-names": "off",
	},
	overrides: [
		{
			// anti-slop was triaged for production code only; the rest mirrors the
			// exemptions biome.jsonc carried for tests.
			files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts"],
			rules: {
				"anti-slop/no-chained-type-assertions": "off",
				"anti-slop/no-conditional-empty-object-spread": "off",
				"anti-slop/no-known-value-widening": "off",
				"anti-slop/no-module-mocking": "off",
				"anti-slop/no-object-parameters": "off",
				"anti-slop/no-reflect-apply": "off",
				"anti-slop/no-reflect-get": "off",
				"anti-slop/no-runtime-typeof": "off",
				"anti-slop/no-unknown-parameters": "off",
				"anti-slop/no-unknown-returns": "off",
				"anti-slop/no-unknown-type-aliases": "off",
				"anti-slop/no-unsafe-dictionary-type": "off",
				"anti-slop/no-widen-then-assert": "off",
				"anti-slop/require-safety-comment-for-type-assertion": "off",
				"typescript/no-non-null-assertion": "off",
				"no-script-url": "off",
				"prefer-arrow-callback": "off",
			},
		},
	],
});
