-- AlterEnum: remove REQUIRE_ORCID from AppSettingKey
-- First delete any rows using this value
DELETE FROM "app_settings" WHERE "key" = 'REQUIRE_ORCID';

BEGIN;
CREATE TYPE "AppSettingKey_new" AS ENUM ('CONFERENCE_NAME', 'CONFERENCE_DATE_START', 'CONFERENCE_DATE_END', 'SUBMISSION_DEADLINE', 'REVIEW_DEADLINE', 'NOTIFICATION_DATE', 'CONTACT_EMAIL', 'CONFERENCE_LOCATION', 'CONFERENCE_WEBSITE', 'MAX_ABSTRACT_LENGTH', 'MAX_FILE_SIZE_MB', 'ALLOWED_FILE_TYPES', 'MAX_AUTHORS', 'ENABLE_KEYWORDS', 'MAX_KEYWORDS', 'SUBMISSION_TYPE_ORAL_PRESENTATION', 'SUBMISSION_TYPE_POSTER', 'SUBMISSION_TYPE_FULL_PAPER', 'MIN_TITLE_LENGTH', 'MAX_TITLE_LENGTH', 'MIN_ABSTRACT_LENGTH', 'MIN_KEYWORDS', 'FEE_PAYMENT_INSTRUCTIONS', 'BRANDING_LOGO_URL', 'BRANDING_FAVICON_URL', 'BRANDING_PRIMARY_COLOR', 'BRANDING_SECONDARY_COLOR', 'BRANDING_FOOTER_TEXT', 'BRANDING_AUTH_BACKGROUND_KEY', 'BRANDING_AUTH_BG_OVERLAY', 'BRANDING_LOGO_DARK_INVERT', 'REMINDER_REVIEWER_SETTINGS', 'REMINDER_REVISION_SETTINGS', 'REMINDER_DEADLINE_SETTINGS', 'CONFERENCE_SUBTITLE', 'SUBMISSION_GUIDELINES', 'REVIEW_GUIDELINES', 'EMAIL_FOOTER_TEXT', 'TOS_CONTENT', 'DATE_FORMAT', 'TIME_FORMAT', 'INVITATION_VALIDITY_HOURS', 'FEE_CURRENCY', 'FEE_TYPES');
ALTER TABLE "app_settings" ALTER COLUMN "key" TYPE "AppSettingKey_new" USING ("key"::text::"AppSettingKey_new");
ALTER TYPE "AppSettingKey" RENAME TO "AppSettingKey_old";
ALTER TYPE "AppSettingKey_new" RENAME TO "AppSettingKey";
DROP TYPE "public"."AppSettingKey_old";
COMMIT;
