import type { EmailEventType } from "../src/generated/prisma/enums";

export interface DefaultEmailTemplate {
	eventType: EmailEventType;
	subject: string;
	body: string;
	isEnabled: boolean;
	isHtml: boolean;
	ccEmails: string[];
	bccEmails: string[];
	availablePlaceholders: string[];
	description: string;
}

export const DEFAULT_EMAIL_TEMPLATES: DefaultEmailTemplate[] = [
	{
		eventType: "SUBMISSION_RECEIVED",
		subject: "Submission Received: {{submissionTitle}}",
		body: 'Dear {{authorName}},\n\nYour submission "{{submissionTitle}}" has been received.\n\nView your submission: {{submissionUrl}}\n\nThank you for your submission.',
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["authorName", "submissionTitle", "submissionUrl"],
		description: "Sent when a new submission is created",
	},
	{
		eventType: "EMAIL_VERIFICATION",
		subject: "Verify your email - {{conferenceName}}",
		body: "Hello {{firstName}},\n\nPlease click the link below to verify your email address:\n\n{{verificationUrl}}\n\nThis link expires in 24 hours.\n\nBest regards,\n{{conferenceName}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["firstName", "verificationUrl", "conferenceName"],
		description: "Sent when a new user registers to verify their email",
	},
	{
		eventType: "PASSWORD_RESET",
		subject: "Reset your password - {{conferenceName}}",
		body: "Hello {{firstName}},\n\nClick the link below to reset your password:\n\n{{resetUrl}}\n\nThis link expires in 1 hour.\n\nBest regards,\n{{conferenceName}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["firstName", "resetUrl", "conferenceName"],
		description: "Sent when a user requests a password reset",
	},
	{
		eventType: "SUBMISSION_WITHDRAWN",
		subject: "Submission Withdrawn: {{submissionTitle}}",
		body: 'Dear {{authorName}},\n\nYour submission "{{submissionTitle}}" has been withdrawn.\n\nView: {{submissionUrl}}\n\nIf you did not request this, please contact us immediately.',
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["authorName", "submissionTitle", "submissionUrl"],
		description: "Sent when an author withdraws their submission",
	},
	{
		eventType: "REVIEWER_ASSIGNED",
		subject: "New Review Assignment: {{submissionTitle}}",
		body: "Dear {{reviewerName}},\n\nYou have been assigned to review the submission:\n\nTitle: {{submissionTitle}}\nDeadline: {{deadline}}\n\nStart your review: {{reviewUrl}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["reviewerName", "submissionTitle", "deadline", "reviewUrl"],
		description: "Sent when a reviewer is assigned to a submission",
	},
	{
		eventType: "REVIEWER_REMINDER",
		subject: "Review Reminder: {{submissionTitle}}",
		body: "Dear {{reviewerName}},\n\nThis is a reminder that your review for the submission:\n\nTitle: {{submissionTitle}}\nDeadline: {{deadline}}\n\nis approaching its deadline. Submit your review: {{reviewUrl}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["reviewerName", "submissionTitle", "deadline", "reviewUrl"],
		description: "Sent as a reminder to reviewers about upcoming deadlines",
	},
	{
		eventType: "REVIEW_SUBMITTED",
		subject: "Review Submitted for: {{submissionTitle}}",
		body: "Dear Editor,\n\nA review has been submitted for the submission:\n\nTitle: {{submissionTitle}}\nReviewer: {{reviewerName}}\n\nView: {{submissionUrl}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["submissionTitle", "reviewerName", "submissionUrl"],
		description: "Sent to editors when a reviewer submits their review",
	},
	{
		eventType: "ALL_REVIEWS_COMPLETE",
		subject: "All Reviews Complete: {{submissionTitle}}",
		body: "Dear Editor,\n\nAll reviews have been completed for the submission:\n\nTitle: {{submissionTitle}}\n\nView: {{submissionUrl}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["submissionTitle", "submissionUrl"],
		description: "Sent to editors when all reviews for a submission are complete",
	},
	{
		eventType: "DECISION_ACCEPTED",
		subject: "Submission Accepted: {{submissionTitle}}",
		body: 'Dear {{authorName}},\n\nWe are pleased to inform you that your submission "{{submissionTitle}}" has been accepted.\n\n{{letterToAuthor}}\n\nView: {{submissionUrl}}\n\nCongratulations!',
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["authorName", "submissionTitle", "letterToAuthor", "submissionUrl"],
		description: "Sent when a submission is accepted",
	},
	{
		eventType: "DECISION_CONDITIONALLY_ACCEPTED",
		subject: "Submission Conditionally Accepted: {{submissionTitle}}",
		body: 'Dear {{authorName}},\n\nYour submission "{{submissionTitle}}" has been conditionally accepted.\n\n{{letterToAuthor}}\n\nView: {{submissionUrl}}\n\nPlease address the conditions outlined above.',
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["authorName", "submissionTitle", "letterToAuthor", "submissionUrl"],
		description: "Sent when a submission is conditionally accepted",
	},
	{
		eventType: "DECISION_REVISE_REQUIRED",
		subject: "Revision Required: {{submissionTitle}}",
		body: 'Dear {{authorName}},\n\nYour submission "{{submissionTitle}}" requires revisions.\n\n{{letterToAuthor}}\n\nResubmit: {{submissionUrl}}',
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["authorName", "submissionTitle", "letterToAuthor", "submissionUrl"],
		description: "Sent when a submission requires revisions",
	},
	{
		eventType: "DECISION_REJECTED",
		subject: "Submission Decision: {{submissionTitle}}",
		body: 'Dear {{authorName}},\n\nWe regret to inform you that your submission "{{submissionTitle}}" has not been accepted.\n\n{{letterToAuthor}}\n\nView: {{submissionUrl}}\n\nThank you for your interest.',
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["authorName", "submissionTitle", "letterToAuthor", "submissionUrl"],
		description: "Sent when a submission is rejected",
	},
	{
		eventType: "REVISION_RECEIVED",
		subject: "Revised Submission Received: {{submissionTitle}}",
		body: "Dear Editor,\n\nA revised version of the submission has been received:\n\nTitle: {{submissionTitle}}\nAuthor: {{authorName}}\nVersion: {{versionNumber}}\n\nView: {{submissionUrl}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["submissionTitle", "authorName", "versionNumber", "submissionUrl"],
		description: "Sent to editors when an author resubmits a revised submission",
	},
	{
		eventType: "REVISION_REMINDER",
		subject: "Revision Reminder: {{submissionTitle}}",
		body: 'Dear {{authorName}},\n\nThis is a reminder that your revised submission "{{submissionTitle}}" is expected.\n\nView: {{submissionUrl}}',
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["authorName", "submissionTitle", "submissionUrl"],
		description: "Sent as a reminder to authors about pending revisions",
	},
	{
		eventType: "DEADLINE_APPROACHING",
		subject: "Deadline Approaching: {{submissionTitle}}",
		body: "Dear {{recipientName}},\n\nThe deadline for {{submissionTitle}} is approaching on {{deadline}}.\n\nView: {{submissionUrl}}\n\nPlease ensure you complete your tasks on time.",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["recipientName", "submissionTitle", "deadline", "submissionUrl"],
		description: "Sent when a deadline is approaching",
	},
	{
		eventType: "INVITATION",
		subject: "You've been invited to {{conferenceName}}",
		body: "Hello,\n\nYou have been invited to join {{conferenceName}} as {{roleName}}.\n\nPlease register using the link below:\n\n{{registrationUrl}}\n\nThis invitation expires on {{expiresAt}}.\n\nBest regards,\n{{conferenceName}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: [
			"conferenceName",
			"roleName",
			"registrationUrl",
			"expiresAt",
		],
		description: "Sent when an admin invites a user to register",
	},
	{
		eventType: "ACCOUNT_CREATED",
		subject: "Welcome to {{conferenceName}}",
		body: "Dear {{firstName}},\n\nYour account has been created successfully.\n\nPlease verify your email address to get started.\n\nBest regards,\n{{conferenceName}}",
		isEnabled: true,
		isHtml: false,
		ccEmails: [],
		bccEmails: [],
		availablePlaceholders: ["firstName", "conferenceName"],
		description: "Sent when a new user account is created",
	},
];
