export const activityLabels: Record<string, string> = {
	USER_REGISTERED: "User registered",
	USER_EMAIL_VERIFIED: "Email verified",
	USER_PROFILE_UPDATED: "Profile updated",
	USER_PASSWORD_CHANGED: "Password changed",
	USER_ROLE_CHANGED: "Role changed",
	USER_TOGGLED_ACTIVE: "User status changed",
	USER_TOGGLED_LATE_SUBMISSION: "Late submission permission changed",
	USER_DELETED: "User deleted",
	SUBMISSION_CREATED: "Submission created",
	SUBMISSION_DRAFT_SUBMITTED: "Draft submitted",
	SUBMISSION_STATUS_CHANGED: "Status changed",
	SUBMISSION_WITHDRAWN: "Submission withdrawn",
	SUBMISSION_RESUBMITTED: "Submission resubmitted",
	SUBMISSION_REVISION_UPLOADED: "Revised version uploaded",
	SUBMISSION_TRACK_CHANGED: "Track changed",
	REVIEW_ASSIGNED: "Reviewer assigned",
	REVIEW_SUBMITTED: "Review submitted",
	REVIEW_CANCELLED: "Review cancelled",
	REVIEW_OVERDUE: "Review overdue",
	DECISION_SUBMITTED: "Decision submitted",
	DECISION_DESK_REJECT: "Desk rejected",
	DECISION_DESK_ACCEPT: "Desk accepted",
	DECISION_OVERRIDE: "Decision overridden",
	INVITATION_CREATED: "Invitation sent",
	INVITATION_USED: "Invitation accepted",
	INVITATION_CANCELLED: "Invitation cancelled",
	FEE_MARKED_PAID: "Fee marked paid",
	FEE_MARKED_UNPAID: "Fee marked unpaid",
	EXHIBITOR_APPLIED: "Exhibitor applied",
	EXHIBITOR_APPROVED: "Exhibitor approved",
	EXHIBITOR_REJECTED: "Exhibitor rejected",
	EXHIBITOR_WITHDRAWN: "Exhibitor withdrawn",
};
